site_name: Проектирование и развертывание веб-решений
site_author: Шаповалова Дарья
site_description: Отчёт о выполнении первой работы по созданию темы и пайплайна

docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    scheme: default
    primary: green
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.top
    - content.tabs
    - content.code.annotate

extra_css:
  - assets/css/style.css

extra_javascript:
  - assets/js/script.js
